<a href="https://colab.research.google.com/github/SSanjey/ssanjey.github.io/blob/main/%5BFODS%5DLab_Evaluation_1_(Python_%26_Numpy_basics).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
my_set = {"aman", "222", 777, 400.4}
my_tuple = tuple(my_set)
print(my_tuple)


('aman', 777, '222', 400.4)


In [2]:
my_dict = {
    "roll_no": 12345,
    "last_name": "Sharma",
    "first_name": "Aman",
    "date_of_birth": "1990-01-01"
}

print("The values in the dictionary are:")
for value in my_dict.values():
    print(value)

print("\nThe keys in the dictionary are:")
for key in my_dict.keys():
    print(key)


The values in the dictionary are:
12345
Sharma
Aman
1990-01-01

The keys in the dictionary are:
roll_no
last_name
first_name
date_of_birth


In [3]:
import random

seed = 12345
array = [[random.randint(0, 100) for col in range(3)] for row in range(3)]
print(array)


[[79, 91, 87], [9, 74, 97], [83, 21, 98]]


In [4]:
import random

random_number = random.random()
print(random_number)

absolute_value = abs(-1234)
print(absolute_value)


0.9083577907721712
1234


In [5]:
import random

random_integer = random.randint(20, 90)
print(random_integer)


55


In [9]:
import numpy as np
pop = [11,12,13,14,15]
np.random.shuffle(pop)
print(pop)
print(pop[random.randint(0,5)])
temp=[pop.pop(random.randint(0,5)),pop.pop(random.randint(0,4)),pop.pop(random.randint(0,3))]
print(temp)


[11, 15, 14, 13, 12]
13
[14, 12, 13]


In [10]:
f = open('test.txt','w')
f.write('The King is Dead, Long Live The King')
f.close()
f = open('test.txt','r')
for i in f:
  print(i,end=" ")
f.close()

The King is Dead, Long Live The King 

In [11]:
dd="The King is Dead, Long Live The King"
print(dd)

The King is Dead, Long Live The King


In [12]:
print(dd[0:1])
print(dd[2:5])
print(dd[2:])

T
e K
e King is Dead, Long Live The King


In [13]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [14]:
print(arr[1])
print(len(arr))

[4 5 6]
2


In [15]:
ar=np.array([1,2,3,4,5,6,7,8,9,0])
print(ar)
ar=ar.reshape(2,5)
print(ar)


[1 2 3 4 5 6 7 8 9 0]
[[1 2 3 4 5]
 [6 7 8 9 0]]


In [16]:
import numpy as np
my_list = [1,2,3]
arr= np.array(my_list)
print(arr)

[1 2 3]


In [18]:
a=[1,2,3]
a=np.full((3),9)
print(a)

[9 9 9]


In [19]:
a=[2,4,5]
print(sum(a))


11


In [20]:
a=[77,74,75]
prod=1
for i in a:
  prod*=i
print(prod)


427350


In [21]:
import numpy as np
from scipy import stats
ttt=np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
print("Mean=",np.mean(ttt))
print("Median=",np.median(ttt))
print("Mode=",stats.mode(ttt))
print("Max=",max(ttt))
print("Min=",min(ttt))

Mean= 12.461538461538462
Median= 2.0
Mode= ModeResult(mode=array([1]), count=array([4]))
Max= 56
Min= 1


<ipython-input-21-e88c675209e8>:6: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print("Mode=",stats.mode(ttt))


In [22]:
a=[1, 1, 4, 5, 5, 5, 7]
a=list(set(a))
a.sort()
print(a)


[1, 4, 5, 7]


In [23]:
a=[1,2,3]
b=[0,1,1]
print(np.dot(a,b))

5


In [25]:
a=[[2,-12],[1,-5]]
x,y=np.linalg.eig(a)
print(x,y)


[-1. -2.] [[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]
